---
title: "Tidy Tuesday"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(scales)
library(gganimate)

# install.packages("tidytuesdayR")
tuesdata <- tidytuesdayR::tt_load('2020-09-22')

peaks <- tuesdata$peaks |> filter(first_ascent_year > 1900)
expeditions <- tuesdata$expeditions


```

```{r}


# popularity of peaks overtime
expeds <- 
  expeditions |> 
  filter(!is.na(peak_name)) |> 
  group_by(year, peak_name) |> 
  count(name = "summits_in_year", sort = T) 

peak_heights <-
  peaks |> 
  select(peak_name, height_metres)

oxy_usage <- 
  

p_data <- 
   expand_grid(year = min(expeditions$year):max(expeditions$year), 
            peak_name = expeditions$peak_name |> unique()) |>
  left_join(expeds) |> 
  mutate(summits_in_year = ifelse(summits_in_year |> is.na(), 0, summits_in_year) |> as.integer()) |> 
  group_by(peak_name) |> 
   mutate(total_summits = cumsum(summits_in_year)) |> 
  ungroup(peak_name) |> 
  group_by(year) %>%
  arrange(year, desc(total_summits)) %>%
  mutate(ranking = row_number()) |> 
  filter(ranking <= 15, total_summits > 0) %>%
  ungroup() |> 
  left_join(peak_heights)

p <- 
  p_data |> 
  # filter(year > 2000) |> 
  # mutate(height_metres = as.numeric(height_metres)) |>
  ggplot() +
  geom_col(aes(ranking, total_summits, fill = peak_name)) +
  geom_text(aes(ranking, total_summits, label = as.character(total_summits)), hjust=-0.1) +
  geom_text(aes(ranking, y=0 , label = peak_name), hjust=1.1) +
  # geom_text(aes(x = 16,
  #               y = max(total_summits),
  #               label = as.factor(year)),
  #           vjust = 0.2, alpha = 0.5,  col = "gray", size = 20) +
  coord_flip(clip = "off", expand = TRUE) + 
  scale_x_reverse() +
  theme_minimal() +
  # scale_fill_continuous(high = "#132B43", low = "#56B1F7") +
  guides(fill=guide_legend(title="Peak height (m)", 
                           title.position = "left", 
                           title.vjust = 1, title.hjust = 0.5)) +
  theme(
    panel.grid = element_blank(), 
    legend.position = "none",
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    axis.text = element_blank(),
    plot.margin = margin(1, 4, 1, 3, "cm"),
    title = element_text(colour = "gray20", size = 20),
    plot.subtitle = element_text(colour = "gray50", size = 30),
    legend.justification = c(1, 1)) +
  transition_states(year, 
                    state_length = 0, 
                    transition_length = 3) +
  # view_follow() +
  labs(title='Total attempts of Himilayan peaks', 
       subtitle = "{closest_state}") +
  enter_fade() +
  exit_fade() + 
  ease_aes('quadratic-in-out') 



p2 <- animate(p, 300, fps = 20, duration = 10, width = 950, height = 750, renderer = gifski_renderer(), end_pause = 30)

anim_save("peaks_time.gif", animation = p2)


```

